//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace swi_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HSItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HSItem()
        {
            this.SWIHSItems = new HashSet<SWIHSItem>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string PrintMessage { get; set; }
        public byte[] Image { get; set; }
        public string Company { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SWIHSItem> SWIHSItems { get; set; }
    }
}
