//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace swi_api.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SWIDB : DbContext
    {
        public SWIDB()
            : base("name=SWIDB")
        {
            this.Configuration.LazyLoadingEnabled = false;
    		this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HSItem> HSItems { get; set; }
        public virtual DbSet<SWICompany> SWICompanys { get; set; }
        public virtual DbSet<SWIHeader> SWIHeaders { get; set; }
        public virtual DbSet<SWIHSItem> SWIHSItems { get; set; }
        public virtual DbSet<SWIObservation> SWIObservations { get; set; }
        public virtual DbSet<SWIPermission> SWIPermissions { get; set; }
        public virtual DbSet<SWIRolePermission> SWIRolePermissions { get; set; }
        public virtual DbSet<SWIRole> SWIRoles { get; set; }
        public virtual DbSet<SWIStage> SWIStages { get; set; }
        public virtual DbSet<SWITag> SWITags { get; set; }
        public virtual DbSet<SWITool> SWITools { get; set; }
        public virtual DbSet<SWIUser> SWIUsers { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<SWIClientApp> SWIClientApps { get; set; }
        public virtual DbSet<SWISecurityToken> SWISecurityTokens { get; set; }
    }
}
