//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace swi_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SWIHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SWIHeader()
        {
            this.SWIHSItems = new HashSet<SWIHSItem>();
            this.SWIStages = new HashSet<SWIStage>();
            this.SWITags = new HashSet<SWITag>();
            this.SWITools = new HashSet<SWITool>();
        }
    
        public int Id { get; set; }
        public int Sequence { get; set; }
        public string Title { get; set; }
        public string Revision { get; set; }
        public bool Released { get; set; }
        public int Author { get; set; }
        public Nullable<int> Expert { get; set; }
        public Nullable<int> Approver { get; set; }
        public int Company { get; set; }
    
        public virtual SWICompany SWICompany { get; set; }
        public virtual SWIUser SWIAuthor { get; set; }
        public virtual SWIUser SWIExpert { get; set; }
        public virtual SWIUser SWIApprover { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SWIHSItem> SWIHSItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SWIStage> SWIStages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SWITag> SWITags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SWITool> SWITools { get; set; }
    }
}
