//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace swi_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SWIObservation
    {
        public int Id { get; set; }
        public int Stage { get; set; }
        public string Text { get; set; }
        public byte[] Image { get; set; }
        public string JobNumber { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    
        public virtual SWIStage SWIStage { get; set; }
        public virtual SWIUser ObservationCreatedBy { get; set; }
        public virtual SWIUser ObservationModifiedBy { get; set; }
    }
}
