//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace swi_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SWIRolePermission
    {
        public int Id { get; set; }
        public int Role { get; set; }
        public int Permission { get; set; }
    
        public virtual SWIPermission SWIPermission { get; set; }
        public virtual SWIRole SWIRole { get; set; }
    }
}
