//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace swi_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SWIStage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SWIStage()
        {
            this.SWIObservations = new HashSet<SWIObservation>();
        }
    
        public int Id { get; set; }
        public int Sequence { get; set; }
        public string Text { get; set; }
        public string ImageCaption { get; set; }
        public byte[] Image { get; set; }
        public bool CriticalStep { get; set; }
        public string CarePoint { get; set; }
        public string Hyperlink { get; set; }
        public Nullable<int> RelatedSwi { get; set; }
        public Nullable<int> SWI { get; set; }
    
        public virtual SWIHeader SWIHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SWIObservation> SWIObservations { get; set; }
    }
}
