//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace swi_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SWISecurityToken
    {
        public int Id { get; set; }
        public System.Guid Token { get; set; }
        public int User { get; set; }
        public string IPAddress { get; set; }
        public string HostPC { get; set; }
        public System.DateTime IssuedOn { get; set; }
        public int Timeout { get; set; }
        public System.DateTime ExpiresOn { get; set; }
        public int ClientApp { get; set; }
        public Nullable<System.DateTime> LoggedOutOn { get; set; }
        public int RefreshCount { get; set; }
    
        public virtual SWIClientApp SWIClientApp { get; set; }
        public virtual SWIUser SWIUser { get; set; }
    }
}
